package com.gjs.developresponsity.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.gjs.developresponsity.model.VideoInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VIDEO_INFO".
*/
public class VideoInfoDao extends AbstractDao<VideoInfo, Long> {

    public static final String TABLENAME = "VIDEO_INFO";

    /**
     * Properties of entity VideoInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property VideoCover = new Property(1, String.class, "videoCover", false, "VIDEO_COVER");
        public final static Property VideoTitle = new Property(2, String.class, "videoTitle", false, "VIDEO_TITLE");
        public final static Property VideoUrl = new Property(3, String.class, "videoUrl", false, "VIDEO_URL");
        public final static Property VideoDescript = new Property(4, String.class, "videoDescript", false, "VIDEO_DESCRIPT");
    }


    public VideoInfoDao(DaoConfig config) {
        super(config);
    }
    
    public VideoInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VIDEO_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"VIDEO_COVER\" TEXT," + // 1: videoCover
                "\"VIDEO_TITLE\" TEXT," + // 2: videoTitle
                "\"VIDEO_URL\" TEXT," + // 3: videoUrl
                "\"VIDEO_DESCRIPT\" TEXT);"); // 4: videoDescript
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VIDEO_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VideoInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String videoCover = entity.getVideoCover();
        if (videoCover != null) {
            stmt.bindString(2, videoCover);
        }
 
        String videoTitle = entity.getVideoTitle();
        if (videoTitle != null) {
            stmt.bindString(3, videoTitle);
        }
 
        String videoUrl = entity.getVideoUrl();
        if (videoUrl != null) {
            stmt.bindString(4, videoUrl);
        }
 
        String videoDescript = entity.getVideoDescript();
        if (videoDescript != null) {
            stmt.bindString(5, videoDescript);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VideoInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String videoCover = entity.getVideoCover();
        if (videoCover != null) {
            stmt.bindString(2, videoCover);
        }
 
        String videoTitle = entity.getVideoTitle();
        if (videoTitle != null) {
            stmt.bindString(3, videoTitle);
        }
 
        String videoUrl = entity.getVideoUrl();
        if (videoUrl != null) {
            stmt.bindString(4, videoUrl);
        }
 
        String videoDescript = entity.getVideoDescript();
        if (videoDescript != null) {
            stmt.bindString(5, videoDescript);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public VideoInfo readEntity(Cursor cursor, int offset) {
        VideoInfo entity = new VideoInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // videoCover
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // videoTitle
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // videoUrl
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // videoDescript
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VideoInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setVideoCover(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setVideoTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setVideoUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setVideoDescript(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(VideoInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(VideoInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(VideoInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
